apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app
  #describes the pod template
  template:
    metadata:
      labels:
        app: messaging-app
    spec:
      containers:
        - name: messaging-container
          image: nicholaskamau/messaging_app:0.0.2
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: messaging_app.settings
            - name: DEBUG
              value: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: messaging-svc
spec:
  selector:
    app: messaging-app
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
